# 命令执行 docker-compose up -d
version: '3.9'
# 不同架构选择不同镜像；AMD ignite:2.15.0 ARM ignite:2.15.0-arm64 https://hub.docker.com/r/apacheignite/ignite/tags
# mysql 8.0.32 支持 AMD/ARM
services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Asia/Shanghai
      #      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' # 可配置无密码，注意配置 SPRING_DATASOURCE_PASSWORD=
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: xfg
      MYSQL_PASSWORD: 123456
    depends_on:
      - mysql-job-dbdata
    ports:
      - "13306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    volumes_from:
      - mysql-job-dbdata

  # 自动加载数据
  mysql-job-dbdata:
    image: alpine:3.18.2
    container_name: mysql-job-dbdata
    volumes:
      - /var/lib/mysql

  ignite:
    image: apacheignite/ignite:2.15.0-arm64
    container_name: ignite
    ports:
      - 10800:10800

  # ab -n 1000 -c 100 https://baidu.com/
  ApacheBench:
    image: anantadwi13/rakyll-hey